//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSystemElements
    {
        public int Id { get; set; }
        public int Id_Owner { get; set; }
        public string Name { get; set; }
        public string Hash { get; set; }
        public string Parent { get; set; }
        public int ElementType { get; set; }
        public byte[] Content { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
