CREATE TABLE Users
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Login NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL
);
CREATE TABLE FileSystemElements
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Id_Owner INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	Name NVARCHAR(100) NOT NULL,
	Hash NVARCHAR(100) NOT NULL,
	Parent NVARCHAR(100) NOT NULL,
	ElementType INT NOT NULL,
	Content VARBINARY(MAX) NULL,
);
USE DropBox;
DROP TABLE Users;
DROP TABLE FileSystemElements;