CREATE DATABASE DropBox;
USE DropBox;
CREATE TABLE FileSystemElements
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Hash NVARCHAR(100) NOT NULL,
	Parent NVARCHAR(100) NOT NULL,
	ElementType INT NOT NULL,
	Content BINARY NULL
);
CREATE TABLE Users
(
	ID INT NOT NULL IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Login NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL
);